### ISSUE TITLE
Updating this to support gpt-4?

### ISSUE THREAD

**Issue by TheWanderer1983** [evyatar9/GptHidra#2]
As title suggests.

**Comment by evyatar9** [comment]
Hi there,

Thank you for your interest in updating the repository to support GPT-4. However, as of now, GPT-4 is still in a limited beta and is not accessible to the general public.

Once GPT-4 becomes available for wider use, I will make sure to update the repository accordingly. In the meantime, feel free to contribute to the repository or suggest any other improvements.

Thank you for your understanding and support!!!
