### ISSUE TITLE
HTTP error 429 too many requests

### ISSUE THREAD

**Issue by 7h3w4lk3r** [evyatar9/GptHidra#4]
![image](https://github.com/evyatar9/GptHidra/assets/61451071/cc29e586-bda4-4e5b-8254-eebad5f2ad7d)

i get this error when i run the script.

**Comment by evyatar9** [comment]
Hi @7h3w4lk3r,
The 429 'Too Many Requests' error occurs when the OpenAI API detects excessive requests within a specific time frame.
This is a rate limit measure implemented by the OpenAI API provider to ensure fair usage by your token.

Thank you for reporting the issue.
