### ISSUE TITLE
GptHidra "cloned" by Ghidra-ChatGPT

### ISSUE THREAD

**Issue by AquosTheWolf** [evyatar9/GptHidra#6]
I found this: https://github.com/wowitsjack/Ghidra-ChatGPT essentially ripoff of GptHidra

Relevant Linkedin post on this "clone": https://www.linkedin.com/posts/wowjackdarcy_github-wowitsjackghidra-chatgpt-complete-activity-7105123101276864512-7PK3?utm_source=share&utm_medium=member_desktop

It's basically a near verbatim clone being claimed as original work, and a port of GPTHIDRA, but if you run a git diff, it's basically identical

**Comment by evyatar9** [comment]
Hi,
THANK YOU very much for letting me know that my project has been copied(!!).
Btw, Now GptHidra support gpt-4!

**Comment by ImanCol** [comment]
work gpt 3.5?

**Comment by evyatar9** [comment]
@ImanCol  - Sure!
https://github.com/evyatar9/GptHidra/releases/tag/GptHidra-GPT-3.5
